apiVersion: v1
kind: ReplicationController
metadata:
  name: test01
spec:
  replicas: 2
  template:
    metadata:
      labels:
         test: test01
    spec:
      containers:
      - name: nginx-test01
        image: nginx
        ports:
        - containerPort: 80
