kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: fluentd-elasticsearch
  namespace: kube-system
  labels:
    k8s-app: fluentd-elasticsearch
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-elasticsearch
  template:
    metadata:
      namespace: kube-system
      labels:
        k8s-app: fluentd-elasticsearch
    spec:
      hostNetwork: true
      containers:
      - name: fluentd-elasticsearch
        image: gcr.io/google_containers/fluentd-elasticsearch:1.11
        resources:
          limits:
            cpu: 100m
        args:
        - -qq
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
